In [5]:
import pandas as pd
path_to_file = 'student_scores.csv'
df = pd.read_csv(path_to_file)
df

FileNotFoundError: [Errno 2] No such file or directory: 'student_scores.csv'

In [5]:
df.head()

Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30

In [7]:
df.shape

(25, 2)

In [1]:
df.plot.scatter(x='Hours', y='Scores', title='Scatter Plot of hours and scores');

NameError: name 'df' is not defined

In [11]:
print(df.corr())

           Hours    Scores
Hours   1.000000  0.976191
Scores  0.976191  1.000000


In [13]:
print(df.describe())

           Hours     Scores
count  25.000000  25.000000
mean    5.012000  51.480000
std     2.525094  25.286887
min     1.100000  17.000000
25%     2.700000  30.000000
50%     4.800000  47.000000
75%     7.400000  75.000000
max     9.200000  95.000000


In [15]:
y = df['Scores'].values.reshape(-1, 1)
X = df['Hours'].values.reshape(-1, 1)

In [17]:
print(df['Hours'].values) # [2.5 5.1 3.2 8.5 3.5 1.5 9.2 ... ]
print(df['Hours'].values.shape) # (25,)

[2.5 5.1 3.2 8.5 3.5 1.5 9.2 5.5 8.3 2.7 7.7 5.9 4.5 3.3 1.1 8.9 2.5 1.9
 6.1 7.4 2.7 4.8 3.8 6.9 7.8]
(25,)


In [19]:
print(X.shape) # (25, 1)
print(X)      # [[2.5] [5.1]  [3.2] ... ]

(25, 1)
[[2.5]
 [5.1]
 [3.2]
 [8.5]
 [3.5]
 [1.5]
 [9.2]
 [5.5]
 [8.3]
 [2.7]
 [7.7]
 [5.9]
 [4.5]
 [3.3]
 [1.1]
 [8.9]
 [2.5]
 [1.9]
 [6.1]
 [7.4]
 [2.7]
 [4.8]
 [3.8]
 [6.9]
 [7.8]]


In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
print(X_train) # [[2.7] [3.3] [5.1] [3.8] ... ]
print(y_train)

In [25]:
print(X_train) # [[2.7] [3.3] [5.1] [3.8] ... ]
print(y_train) # [[25] [42] [47] [35] ... ]

[[9.2]
 [2.7]
 [6.1]
 [2.5]
 [3.2]
 [3.5]
 [5.9]
 [7.7]
 [7.8]
 [4.5]
 [5.5]
 [3.3]
 [5.1]
 [1.1]
 [2.5]
 [7.4]
 [2.7]
 [6.9]
 [8.5]
 [1.9]]
[[88]
 [30]
 [67]
 [30]
 [27]
 [30]
 [62]
 [85]
 [86]
 [41]
 [60]
 [42]
 [47]
 [17]
 [21]
 [69]
 [25]
 [76]
 [75]
 [24]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
print(X_train) 
print(y_train)

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

import pandas as pd
path_to_file = 'student_scores.csv'
df = pd.read_csv(path_to_file)
y = df['Scores'].values.reshape(-1, 1)
X = df['Hours'].values.reshape(-1, 1)
print(df['Hours'].values) # [2.5 5.1 3.2 8.5 3.5 1.5 9.2 ... ]
print(df['Hours'].values.shape) # (25,)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
print(X_train) # [[2.7] [3.3] [5.1] [3.8] ... ]
print(y_train)
regressor = LinearRegression()
regressor.fit(X_train, y_train)#The fit() method trains the linear regression model on the training data (X_train and y_train).
print(regressor.intercept_)#intercept indicates the starting point of the line on the y-axis
print(regressor.coef_)#represent how much the dependent variable is expected to change with a one-unit change in the corresponding independent variable
score = regressor.predict([[9.5]])
print(score) # 94.80663482
y_pred = regressor.predict(X_test)
df_preds = pd.DataFrame({'Actual': y_test.squeeze(), 'Predicted': y_pred.squeeze()})
print(df_preds)

from sklearn.metrics import mean_absolute_error, mean_squared_error

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print(f'Mean absolute error: {mae:.2f}')
print(f'Mean squared error: {mse:.2f}')
print(f'Root mean squared error: {rmse:.2f}')
#Using MAE, MSE, and RMSE helps you understand the performance of your linear regression model from different perspectives. 
#Together, they provide a comprehensive view of the model's accuracy and help in diagnosing
#issues such as large prediction errors, allowing you to refine your model for better performance.

[2.5 5.1 3.2 8.5 3.5 1.5 9.2 5.5 8.3 2.7 7.7 5.9 4.5 3.3 1.1 8.9 2.5 1.9
 6.1 7.4 2.7 4.8 3.8 6.9 7.8]
(25,)
[[5.1]
 [6.1]
 [3.5]
 [3.3]
 [8.5]
 [8.9]
 [2.7]
 [9.2]
 [2.7]
 [7.8]
 [7.4]
 [1.5]
 [2.5]
 [1.9]
 [4.5]
 [2.5]
 [6.9]
 [5.9]
 [8.3]
 [5.5]]
[[47]
 [67]
 [30]
 [42]
 [75]
 [95]
 [25]
 [88]
 [30]
 [86]
 [69]
 [20]
 [21]
 [24]
 [41]
 [30]
 [76]
 [62]
 [81]
 [60]]
[3.14311317]
[[9.6097205]]
[[94.43545794]]
   Actual  Predicted
0      17  13.713806
1      27  33.894219
2      54  49.269772
3      85  77.137961
4      35  39.660051
Mean absolute error: 5.49
Mean squared error: 32.85
Root mean squared error: 5.73
